### ISSUE TITLE
SVG Support in Spine fails in some cases

### ISSUE THREAD

**Issue by rkwright** [readium/SDKLauncher-OSX#39]
EPUB TestSuite 100 has a single page at the end which is SVG content in the spine. This used to work fine, but as of 0.16 it doesn't appear to.  It does render OK in the iOS Launcher and the Chrome extension for 0.16.  Also, SmokeTestFXL, which has several pages of SVG in the spine, works fine.  So this appears to be a regression which appears circa 0.16.

**Comment by danielweck** [comment]
Works fine here (all latest code from develop). Also tested with the latest cloud reader / chrome extension (to compare the rendering).

**Comment by rkwright** [comment]
Long since fixed.  Closing.
