### ISSUE TITLE
Fixed Layout SVG in Spine is  not scaled properly in two-up presentation

### ISSUE THREAD

**Issue by rkwright** [readium/SDKLauncher-OSX#40]
When some fixed layout EPUBs are rendered which contain SVG in the spine, the scaling of some of the pages is incorrect.  Sample file is here:

https://readiumfoundation.box.com/shared/static/linb464eycop0bsmoshx2e01z4m2pbgx.epub
The page following the property description renders correctly if it is not in two-up mode, but in two-up mode, the orange circle is very small and in the upper left-hand corner of the page.

**Comment by danielweck** [comment]
I can reproduce this with the cloud reader (SVGGraphicsInSpine.epub test file provided by Kathy)

**Comment by danielweck** [comment]
Fixed here:
https://github.com/readium/readium-shared-js/commit/1375f2de8ab214e352fb8ac863a71db150da84da
