### ISSUE TITLE
Jenkins continuous integration builds server is down

### ISSUE THREAD

**Issue by kant** [readium/SDKLauncher-OSX#41]
Both links on https://github.com/readium/SDKLauncher-OSX/blob/master/README.md not working up to now.

**Comment by danielweck** [comment]
I guess you mean:

http://jenkinsmaster.datalogics-cloud:8080/view/Readium-Launcher/job/Readium-SDK-Launcher-Mac-OSX-develop/

(renaming this issue's title)

**Comment by danielweck** [comment]
@datalogics-bhaugen any idea?

**Comment by rkwright** [comment]
I pinged Brandon: He said "I'll take a look at this tonight. Wouldn't surprise me if they went down over the last little while. I'll get them functioning again."

**Comment by datalogics-bhaugen** [comment]
Sorry for getting to this later than I intended to, it should be fixed in develop as of 0946e2a6d259

**Comment by probonopd** [comment]
Similarly, https://github.com/readium/SDKLauncher-OSX/pull/42

**Comment by danielweck** [comment]
Fixed by @datalogics-bhaugen https://github.com/readium/SDKLauncher-OSX/commit/0946e2a6d259a4c84b01dc0a42219a1e6f8949e9
